apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-currency-slackbot
spec:
  schedule: "0 0 * * *"
  startingDeadlineSeconds: 60
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: cron-currency-slackbot
            image: ysakashita/currency-slackbot:version-0.1
            envFrom:
            - secretRef:
                name: currency-slackbot
